server:
  port: ${PORT}
spring:
  application:
    name: interview_helper
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  profiles:
    include: oauth


jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity: ${ACCESS_TOKEN_VALIDITY}
  refresh-token-validity: ${REFRESH_TOKEN_VALIDITY}